[tools]
node = "22.16.0"
"npm:@anthropic-ai/claude-code" = "1.0.35"
pnpm = "10.12.1"

[settings]
experimental = true

[hooks]
postinstall = "pnpm install"

[env]
_.path = "node_modules/.bin"
_.file = ".env"

[tasks.dev]
run = "astro dev"

[tasks.build]
run = "astro build"

[tasks.preview]
run = "wrangler dev ./dist/_worker.js"
depends = ["build"]

[tasks.astro]
run = "astro"

[tasks.deploy]
run = "tsx alchemy.run.ts"

[tasks.destroy]
run = "tsx alchemy.run.ts --destroy"

[tasks.fmt]
run = "biome check --write --unsafe ."

[tasks.emails]
run = "email dev -d src/emails"

[tasks."open:deployment"]
run = "open https://dash.cloudflare.com/${CLOUDFLARE_ACCOUNT_ID}/workers/services/view/sideprojectsaturday/production/metrics"

[tasks.logs]
run = "wrangler tail sideprojectsaturday"

[tasks."gen:better-auth"]
run = "npx @better-auth/cli@latest generate --config src/lib/auth.ts"

[tasks."migrate:create"]
run = '''
MIGRATION_OUTPUT=$(wrangler d1 migrations create sps-db {{arg(name="migration_name")}})
MIGRATION_FILE=$(echo "$MIGRATION_OUTPUT" | grep -o "prisma/migrations/[0-9]*_.*\.sql" | head -1)
prisma migrate diff --from-empty --to-schema-datamodel ./prisma/schema.prisma --script --output "$MIGRATION_FILE"
'''

[tasks."migrate:dev"]
run = ["prisma generate", "wrangler d1 migrations apply DB --local"]

[tasks."migrate:prod"]
run = ["prisma generate", "wrangler d1 migrations apply DB --remote"]
