[tools]
node = "22.16.0"
pnpm = "10.12.1"

[settings]
experimental = true

[hooks]
postinstall = "pnpm install"

[env]
_.path = "node_modules/.bin"
_.file = ".env"

[tasks.dev]
run = "astro dev"

[tasks.build]
run = "astro build"

[tasks.preview]
run = "wrangler dev ./dist/_worker.js"
depends = ["build"]

[tasks.astro]
run = "astro"

[tasks.deploy]
run = "tsx alchemy.run.ts"

[tasks.destroy]
run = "tsx alchemy.run.ts --destroy"

[tasks.fmt]
run = "biome check --write --unsafe ."

[tasks."open:deployment"]
run = "open https://dash.cloudflare.com/${CLOUDFLARE_ACCOUNT_ID}/workers/services/view/sideprojectsaturday/production/metrics"

[tasks.logs]
run = "wrangler tail sideprojectsaturday"
