[tools]
node = "22.12.0"
"npm:@actor-core/cli" = "0.8.0"
"npm:@biomejs/biome" = "1.9.4"
"npm:wrangler" = "4.5.1"
pnpm = "9.15.1"

[tasks]
deploy = "wrangler deploy"
dev = "wrangler dev --port 6420"
start = "wrangler dev --port 6420"
cf-typegen = "wrangler types"
check-types = "tsc --noEmit"
fmt = "biome format --fix ."

[env]
_.path = "./node_modules/.bin"
