[tools]
node = "22.12.0"
"npm:@actor-core/cli" = "0.8.0"
pnpm = "9.15.1"


[env]
_.path = "./node_modules/.bin"

[tasks]
deploy = "pnpm run deploy"
dev = "pnpm run dev"
start = "pnpm run start"
cf-typegen = "pnpm run cf-typegen"
check-types = "pnpm run check-types"
fmt = "pnpm run fmt"
