// Generated by Wrangler by running `wrangler types`

interface Env {
	ACTOR_KV: KVNamespace;
	SWITCHBOT_DEVICE_ID: string;
	SWITCHBOT_TOKEN: string;
	SWITCHBOT_KEY: string;
	BUZZER_SECRET: string;
	ACTOR_DO: DurableObjectNamespace<import("./src/index").ActorHandler>;
}
